# Site settings
title: RaspInLoop
email: admin@raspinloop.org
description:  # this means to ignore newlines until "baseurl:"
  Simulate and debug java applications witten with Pi4J Project on Raspberry Pi.
  RaspInLoop allows debugger to interract with computer simulation software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://raspinloop.org" # the base hostname & protocol for your site
github_username:  raspinloop
twitter_username: raspinloop

# Build settings
markdown: kramdown
