url: https://raspinloop.github.io
baseurl: ""

# Site settings
title: RaspInLoop
email: admin@raspinloop.org
description: "Simulate and debug java applications written with Pi4J Project on Raspberry Pi. RaspInLoop allows debugger to interract with computer simulation software."

collections:
    - packages

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/raspinloop
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/raspinloop
  - title: github
    url: http://github.com/RaspInLoop

# Build settings
markdown: kramdown
permalink: pretty
